# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mison < Formula
  desc "Reproduce your development environment anywhere (mise + GitHub)"
  homepage "https://github.com/dev-hann/mison"
  version "0.5.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dev-hann/mison/releases/download/v0.5.6/mison_darwin_amd64.tar.gz"
      sha256 "12d92d455a53405f25b039a05d4e740ff23bc18d98c2b8ee5d8f0d3c7c7ba9f3"

      define_method(:install) do
        bin.install "mison"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dev-hann/mison/releases/download/v0.5.6/mison_darwin_arm64.tar.gz"
      sha256 "975f5232da8254ed21894a1484a5ec3ad47b11b013a59286855916ca147f9260"

      define_method(:install) do
        bin.install "mison"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dev-hann/mison/releases/download/v0.5.6/mison_linux_amd64.tar.gz"
      sha256 "a5d43c5028806e39b5775f556a3726280969d147988add0a0454ca9354c49069"
      define_method(:install) do
        bin.install "mison"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dev-hann/mison/releases/download/v0.5.6/mison_linux_arm64.tar.gz"
      sha256 "77a838c22400dee255fe9bd6e0b728b41c1263556430cdcc6aea7aa39fd813fa"
      define_method(:install) do
        bin.install "mison"
      end
    end
  end

  def caveats
    <<~EOS
      The installer (curl https://raw.githubusercontent.com/dev-hann/mison/main/scripts/install.sh | sh)
      keeps the binary in ~/.local/bin. Pick ONE install method and stick to it.
    EOS
  end
end
